### ISSUE TITLE
Create and prepare dataset

### ISSUE THREAD

**Issue by patricsteiner** [taga5/image_clustering#1]
- [x] Amount: a couple 100 images should be a good start
- [x] Automation: create script that prepares the dataset. Images should be resized to a reasonable size (e.g. width = 240px) to make feature extraction easier and faster

**Comment by taga5** [comment]
[ ] Amount: around 1000 images should be a good start
[ ] Image size: images should be resized to a reasonable size (e.g. width = 240px) to make feature extraction easier and faster

**Comment by taga5** [comment]
- [ ] Amount: around 1000 images should be a good start
- [ ] Image size: images should be resized to a reasonable size (e.g. width = 240px) to make feature extraction easier and faster

**Comment by taga5** [comment]
asd
